### ISSUE TITLE
Consider only using preferred locale set in MSYS2 or Linux or Mac-OS before launching D-Rats.

### ISSUE THREAD

**Issue by maurizioandreotti** [ham-radio-software/D-Rats#236]
The user should have their preferred locale set in MSYS2 or Linux or Mac-OS before launching D-Rats, so we really should not need a locale setting in the config file or from selecting the option in D-Rats.

Maybe we just need to have better instructions on setting the locale for users and stop trying to change it in D-Rats?

_Originally posted by @wb8tyw in https://github.com/ham-radio-software/D-Rats/pull/225#discussion_r1301663968_

As the current D-Rats shows english as default language due to the fact that the labels in the code are in english, and the english .PO is loaded only afterwards in a second step and only partially, i.e as the untranslated labels are in english it just seems to be working correctly.  
so, If i am not mistaken, removing the language selection in the config would mean anyhow to make d-rats load correctly the PO files depending by the local setting.

My Macbook has italian as default language, but I dont see the italian translation when it starts. It think to recall that years ago it was loading on my windows with some italian words (as locale) even if d-rats was configured in the config to be english.

I thought it was of some interest to try to fix this, but, considering that all  licensed hamradio guys need to know anyhow english and that I don't recall anybody complaining about broken translations,  it could also be that we could get rid completely of the translation stuff and gain some faster execution of the program.

**Comment by wb8tyw** [comment]
I think we are almost there with getting the internationalization to just work.

I do not think that GTK supports changing the language after it has loaded a glade file.

I think what we are doing now is defaulting to English locale instead of the current locale set by the user and then looking in the config settings for the user's locale.   And I do not think GTK supports that.

Option one:  Deprecate and ignore the setting in the config file completely and use the locale provided by the OS.
Option two: Use the locale from the config file, and require a complete restart of D-RATS for a change.

Related problem, I recall some thing, I think,QSTs that are using the internationalized text as a key to their data stored in a file.  Change the locale, and the data file is broken.
