### ISSUE TITLE
file -> preferences -> gps -> lookup : coloums in the address results are fixed 

### ISSUE THREAD

**Issue by maurizioandreotti** [ham-radio-software/D-Rats#288]
During a test done with mobaxterm for PR287 i noted that the window with the lookup addresses results has fixed coloums: this doesnt allow to see the correct address to pick up the right coordinates.

in my case, loocking for my qth i getseveral options:

![image](https://github.com/ham-radio-software/D-Rats/assets/7696314/3d39f472-5313-475c-b6f0-257a163cf4fb)

but without enlarging the first coloumn i cannot check which one is the correct

**Comment by wb8tyw** [comment]
The proper fix for this is going to require making changes to the drats/listwidget.py to have a way to tell it how wide to make each column, and that looks like a more complex job.

The behaviour can be improved by changing the order of the fields so that the address is last, so that it will automatically expand by making the box wider, instead of having to make the box wider and then expand the address field.

I am also able to get the box to expand when the search address starts getting longer than the default entry size, and the box will retain that size when you move on to the locations found section, it stays expanded.

**Comment by wb8tyw** [comment]
With this change, if you select a location, and then click next for the confirm address.   The dialog box will be expanded to show it.

If you then click on back, button because you selected the wrong one, the box will remain expanded, and you should be able to see enough of the addresses to make a better selection.

**Comment by wb8tyw** [comment]
Also I found that if no addresses were found, the routine crashed with a stackdump.

**Comment by maurizioandreotti** [comment]
Tested on mac and it seems ok.

**Comment by wb8tyw** [comment]
I do not fully understand the address format in the E-mail you sent me.

To me the "Via <name>" is something for postal routing, but may not mean anything for a GPS lookup.
So I entered in just the "##, ##### C<name> LC (Italy)" for the address.

This comes up with an address very close but not exactly to what you sent me for your Google Maps lookup of your address.

I used the set point on map function with address lookup, and noticed that it placed the looked up address in the "Name" field where logically I think it should be in the comment field.   Something : to look at later.

I have pushed a fix to stop the trace back when an address is not found.   It blanks out part of the dialog, but you can click on the "Back" button to make corrections.

**Comment by maurizioandreotti** [comment]
"via" it the italian word which means "street"

Il giorno dom 28 lug 2024 alle ore 22:50 John E. Malmberg <
***@***.***> ha scritto:

**Comment by wb8tyw** [comment]
Since we are just passing the address to the lookup service, we have no control over if it understands the address or can resolve it.

I think we have worked around the problem for now.
